<footer class="bg-dark text-white py-4">
  <div class="container text-center">
    <h2 class="fw-bold">MyBlog</h2>
    <p>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus neque,
      quaerat, beatae commodi sunt deserunt nesciunt earum adipisci aliquam
      dolor tempore dolore? Id consequuntur rerum odit quis facilis doloribus
      qui?
    </p>
  </div>
  <div class="d-flex flex-wrap justify-content-center">
    <a class="badge bg-secondary fs-8 p-2 m-2 text-decoration-none" href=""
      >Privacy polivy</a
    >
    <a class="badge bg-secondary fs-8 p-2 m-2 text-decoration-none" href=""
      >Privacy polivy</a
    >
    <a class="badge bg-secondary fs-8 p-2 m-2 text-decoration-none" href=""
      >Privacy polivy</a
    >
    <a class="badge bg-secondary fs-8 p-2 m-2 text-decoration-none" href=""
      >Privacy polivy</a
    >
    <a class="badge bg-secondary fs-8 p-2 m-2 text-decoration-none" href=""
      >Privacy polivy</a
    >
  </div>
  <div class="credits text-center mt-4">
    <p>Made by Andres Parra &copy; 2021. All right reserved</p>
  </div>
</footer>
